App.open("C:\Program Files (x86)\Steam\steamapps\common\BountyOfOne\BountyOfOne.exe")
App.focus("BountyOfOne")

wait("main_menu.png",45)
click("encyclopedia_button.png")
wait("encyclopedia.png",45)
click("encyclopedia_objects_button.png")
wait("encyclopedia_objects.png",45)
click("encyclopedia_upgrades_button.png")
wait("encyclopedia_upgrades.png",45)
click("encyclopedia_enemies_button.png")
wait("encyclopedia_enemies.png",45)
click("encyclopedia_characters_button.png")
wait("encyclopedia_characters.png",45)
click("encyclopedia_credits_button.png")
wait("encyclopedia_credits.png",45)
click("encyclopedia_back_button.png")
wait("main_menu.png",45)

closeApp("C:\Program Files (x86)\Steam\steamapps\common\BountyOfOne\BountyOfOne.exe")