App.open("C:\ProgramFilesX86\Steam\steamapps\common\BountyOfOne\BountyOfOne.exe")
App.focus("BountyOfOne")

wait("main_menu.png",45)
wait("start_button.png",45)
wait("blackmarket_button.png",45)
wait("encyclopedia_button.png",45)
wait("leaderboard_button.png",45)
wait("settings_button.png",45)
click("quit_button.png")