doubleClick(Pattern("game_shortcut.png").similar(0.50))
wait("main_menu.png",45)
click("leaderboard_button.png")
wait("leaderboard.png",45)
click("leaderboard_back_to_menu.png")
wait("main_menu.png",45)
click("quit_button.png")